name: iOS build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build (Bloom)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./Bloom
      - name: Build (BloomCS)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./BloomCS
      - name: Build (BloomLossyCompression)
        run: |
          xcodebuild -configuration release -sdk iphonesimulator
        working-directory: ./BloomLossyCompression
      - name: Cache (FCRNFP16.mlmodel)
        id: cache-fcrnfp16-mlmodel
        uses: actions/cache@v3
        with:
          path: ./CoreMLDepthPrediction/CoreMLDepthPrediction/FCRNFP16.mlmodel
          key: dl-build-CoreMLDepthPrediction-01
      - if: ${{ steps.cache-fcrnfp16-mlmodel.outputs.cache-hit != 'true' }}
        name: Download (FCRNFP16.mlmodel)
        continue-on-error: true
        run: |
          curl -s -o FCRNFP16.mlmodel https://ml-assets.apple.com/coreml/models/Image/DepthEstimation/FCRN/FCRNFP16.mlmodel
        working-directory: ./CoreMLDepthPrediction/CoreMLDepthPrediction
      - name: Build (CoreMLDepthPrediction)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./CoreMLDepthPrediction
      - name: Build (CrashDebug)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./CrashDebug
      - name: Build (GpuParticle)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./GpuParticle
      - name: Build (GpuParticleSparseBindingBuffer)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./GpuParticleSparseBindingBuffer
      - name: Build (MeshShader)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./MeshShader
      - name: Build (MeshShaderCulling)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./MeshShaderCulling
      - name: Build (MeshShaderObjectShader)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./MeshShaderObjectShader
      - name: Build (RaytracingPipeline)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./RaytracingPipeline
      - name: Build (ParallelRenderCommand)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ParallelRenderCommand
      - name: Build (RetainedReferences)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./RetainedReferences
      - name: Build (RasterOrderGroupAlphaBlend)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./RasterOrderGroupAlphaBlend
      - name: Build (RasterOrderGroupOIT)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./RasterOrderGroupOIT
      - name: Build (ShadowMap)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMap
      - name: Build (ShadowMapArgumentBuffer)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMapArgumentBuffer
      - name: Build (ShadowMapGpuCommandBuffer)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMapGpuCommandBuffer
      - name: Build (ShadowMapHeapTracking)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMapHeapTracking
      - name: Build (ShadowMapIndirectCommandBuffer)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMapIndirectCommandBuffer
      - name: Build (ShadowMapManualTracking)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./ShadowMapManualTracking
      - name: Build (SimpleDraw)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./SimpleDraw
      - name: Build (SimpleRaytracing)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./SimpleRaytracing
      - name: Build (SimpleTexture)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./SimpleTexture
      - name: Build (SimpleTriangle)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./SimpleTriangle
      - name: Build (SimpleTriangl2)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./SimpleTriangle2
      - name: Build (Tessellation)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./Tessellation
      - name: Build (Tessellation2)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./Tessellation2
      - name: Build (TessellationAdaptive)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: ./TessellationAdaptive
      - name: Build (WaveParticle)
        run: |
          xcodebuild -configuration Release -sdk iphonesimulator
        working-directory: .WaveParticle

